name: Deploy to Production (tracker.cwapolitical.org)

on:
  workflow_run:
    workflows: ["Release and Build Artifacts"]
    types:
      - completed

jobs:
  deploy-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Dist Artifacts
        uses: actions/download-artifact@v4
        with:
          name: workspace-dist
          path: dist/

      - name: Prepare App Config
        run: |
          echo '${{ secrets.APP_CONFIG_JSON }}' > dist/apps/portal-web/config.json

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKER_CWAPOLITICAL_ORG }}"
          projectId: tracker-cwapolitical-org
          channelId: live
