name: Reusable - Deploy to Firebase

on:
  workflow_call:
    inputs:
      environmentId:
        required: true
        type: string
        description: "The Firebase Hosting channel or 'live'"
      projectId:
        required: true
        type: string
        default: "tracker-cwapolitical-org"
    secrets:
      FIREBASE_SERVICE_ACCOUNT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend/functions/lib

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{ inputs.projectId }}
          channelId: ${{ inputs.environmentId }}

          target: hosting,functions
